# Generated by Django 5.0.7 on 2024-12-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chatbot_question_alter_chatbot_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=50),
        ),
    ]
