# Generated by Django 5.0.7 on 2024-12-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=500),
        ),
    ]
