# Generated by Django 5.1.5 on 2025-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='reply',
            field=models.TextField(),
        ),
    ]
